version: '3.4'

x-common-variables: &environment
    INFURA_API_KEY: ${INFURA_API_KEY:-""}

services:
    nginx:
        image: nginx:1.25-alpine
        ports:
            - "9001:80"
        volumes:
            - .:/srv/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - baltbit

    php-fpm:
        build:
            dockerfile: php.Dockerfile
        environment: *environment
        volumes:
            - .:/srv/www
        networks:
            - baltbit

    install-composer:
        build:
            dockerfile: php.Dockerfile
        depends_on:
            - php-fpm
        volumes:
            - .:/srv/www
        command: sh -c "/srv/www/install.sh"
        networks:
            - baltbit

networks:
    baltbit:
